# Generated by Antigravity
# Builder Stage
FROM node:18-alpine AS builder

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY tsconfig.json ./
COPY src/ ./src/

RUN npm run build


# Production Stage
FROM node:18-alpine AS release

# Run as non-root for security (required for Glama inspectability)
RUN addgroup -S rootvine && adduser -S rootvine -G rootvine

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci --omit=dev && npm cache clean --force

COPY --from=builder /app/dist ./dist

# Switch to non-root user
USER rootvine

ENV NODE_ENV=production

# The MCP server uses stdio for communication
ENTRYPOINT ["node", "dist/index.js"]
